### ISSUE TITLE
Couldn't get it to work in OSX

### ISSUE THREAD

**Issue by TaiSHiNet** [NHDaly/tmux-scroll-copy-mode#1]
tmux version 2.1
Used tmp, plugin shows as installed, MacBook Pro touchpad

Any pointers to where might the issue be?

**Comment by NHDaly** [comment]
Hmm, not sure. Did you source your .tmux.conf after installing it again, too? I'm not 100% familiar with how tpm works, so that might be necessary?

You can try running `tmux list-keys -T root` from inside a tmux session. This should tell you what your WheelUpPane is bound to.

For me, it looks like this (the last line is the important one):

```
🏠 $ tmux list-keys -T root
bind-key -T root MouseDown1Pane   select-pane -t = ; send-keys -M
bind-key -T root MouseDown1Status select-window -t =
bind-key -T root MouseDown3Pane   select-pane -m -t =
bind-key -T root MouseDrag1Pane   if-shell -F -t = #{mouse_any_flag} "if -Ft= "#{pane_in_mode}" "copy-mode -M" "send-keys -M"" "copy-mode -M"
bind-key -T root MouseDrag1Border resize-pane -M
bind-key -T root WheelUpPane      if-shell -F -t = #{mouse_any_flag} "send-keys -M" "if -Ft= '#{pane_in_mode}' 'send-keys -M' "copy-mode -e""
```

**Comment by radarek** [comment]
It doesn't work for me either. Here is output from above command:

```
bind-key -T root MouseDown1Pane   select-pane -t = ; send-keys -M
bind-key -T root MouseDown1Status select-window -t =
bind-key -T root MouseDown3Pane   select-pane -m -t =
bind-key -T root MouseDrag1Pane   if-shell -F -t = #{mouse_any_flag} "if -Ft= "#{pane_in_mode}" "copy-mode -M" "send-keys -M"" "copy-mode -M"
bind-key -T root MouseDrag1Border resize-pane -M
bind-key -T root WheelUpPane      if-shell -F -t = #{mouse_any_flag} "send-keys -M" "if -Ft= '#{pane_in_mode}' 'send-keys -M' "copy-mode -e""
bind-key -T root S-Left           previous-window
bind-key -T root S-Right          next-window
```

Scrolling in iTerm does nothing. In Terminal it goes back in command line history (like upper arrow in keyboard).

**Comment by NHDaly** [comment]
This is weird. :/ I'm also on tmux on a macbook pro (but OS 10.10.5 Yosemite, I dunno if that matters).

This command came from https://github.com/tmux/tmux/issues/145. Maybe some of the comments there can help? Please let me know if they do!

**Comment by chrisortman** [comment]
Same as @radarek

**Comment by chrisortman** [comment]
@radarek @TaiSHiNet what command are you using to turn on mouse support? I found I had to change mine to get it working

  # Enable mouse support (works in iTerm)
  set-option -g -q mouse on

**Comment by NHDaly** [comment]
Oh, huh. For me, i was able to do it with just 

```
set-option -g mouse on
```

**Comment by TaiSHiNet** [comment]
Don't you break selection with that? (I recall from linux that mouse options did that)
Currently mostly AFK, sorry that I haven't been able to get back at you guys

**Comment by chrisortman** [comment]
@NHDaly you're right, -q isn't needed

I realized I had just not changed the setting at all from pre 2.1 though, so before I had

setw -g mode-mouse on

And after I changed it to set-option it started working

**Comment by radarek** [comment]
Thanks guys! I removed `set -g mode-mouse on` because tmux said it doesn't know that option and didn't give me any advice that it changed to other name ;-). After replacing it with `set-option -g mouse on` it works now.

Btw, is there a way to increase scrolling speed?

**Comment by NHDaly** [comment]
I've added a comment to README to clarify that you need to set the mouse option in 2.1 to `set-option -g mouse on`. Hopefully this clarifies things for others! :)

Fixed in e0139cae255a046fe05bb977b8eecb6c4c5952e9.

**Comment by NHDaly** [comment]
@radarek: I just added 4d917914e1c03dd8642ab3 which lets you set the scrolling speed. The default is now 3 lines per scroll, to match the scroll speed in tmux 2.0.

Thanks for the suggestion!

**Comment by steveinatorx** [comment]
just a note for those who land on this page - with a mac brew tmux 2.1, el capitan, and Terminal.app system i had to install the SIMBL plugin https://github.com/saitoha/mouseterm-plus/releases to get my Terminal app to register mouse events. The original mouseterm URL from bitheap didnt resolve.  Great plugin thanks @NHDaly

**Comment by crazyhottommy** [comment]
It works to scroll up and down, but it does not highlight the selected

**Comment by crazyhottommy** [comment]
`Prefix + ] `will paste whatever I selected. thanks!
