### ISSUE TITLE
full screen / no mouse scrolling doesn't work in tmux 2.2

### ISSUE THREAD

**Issue by stfl** [NHDaly/tmux-scroll-copy-mode#19]
I noticed, that mouse scrolling in man pages, less and vim (and probably others) doesn't work anymore with tmux 2.2 (from debian testing)

I have the feature set in .tmux.conf

```
set -g @emulate-scroll-for-no-mouse-alternate-buffer 'on'
```

<prefix>? tells me I have these defined:

```
bind-key    -T root   WheelUpPane      if-shell -F -t = #{mouse_any_flag} "send-keys -M" "         if -Ft= ''           'send-keys up ; send-keys up ; send-keys up ; send-keys up ; send-keys up ; '           "                          if -Ft= '#{pane_in_mode}'               'send-keys -M ; send-keys -M ; send-keys -M ; send-keys -M ; send-keys -M ; '               'copy-mode ; send-keys -M ; send-keys -M ; send-keys -M ; send-keys -M ; send-keys -M ; '           "       "
bind-key    -T root   WheelDownPane    if-shell -F -t = #{mouse_any_flag} "send-keys -M" "         if -Ft= ''           'send-keys down ; send-keys down ; send-keys down ; send-keys down ; send-keys down ; '           ' send-keys -M ; send-keys -M ; send-keys -M ; send-keys -M ; send-keys -M ; '       "
```

leaving copy-mode at the bottom of the screen doesn't work either.

**Comment by NHDaly** [comment]
My recommendation: make sure your tmux plugin `tmux-scroll-copy-mode` is up to date.

That output is what it looks like if you're running an older version of the plugin. If you installed using [Tmux Plugin Manager (tpm)](https://github.com/tmux-plugins/tpm), you need to run the update command, and then type `all`, or just `tmux-scroll-copy-mode`.

By default, unless you've changed it, update your plugins with `<prefix>U`.

After you do that, can you let me know how it looks? Thanks!

**Comment by zeorin** [comment]
I've got this same issue. Using Urxvt + Tmux 2.2 + TPM, all plugins updated. Relevant settings:

```
set-option -g mouse on
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'NGDaly/tmux-scroll-copy-mode'
set -g @scroll-down-exit-copy-mode "on"
set -g @scroll-in-moused-over-pane "on"
set -g @scroll-without-changing-pane "on"
set -g @emulate-scroll-for-no-mouse-alternate-buffer "on"
set -g @prevent-scroll-for-fullscreen-alternate-buffer "on"
run '~/.tmux/plugins/tpm/tpm'
```
- Scrolling in NeoVim works quite well
- Scrolling in Vim is broken (scrolling enters copy mode but doesn't scroll).
- Scrolling in Vim when another pane is active puts that pane in copy-mode without actually scrolling it or the Vim pane (NeoVim works as expected).
- Scrolling in a plain terminal pane works quite well, but doesn't exit copy mode at the bottom.
- Scrolling in Less is broken (scrolling shows more of the terminal history).

I have the same problems in Gnome Terminal as Urxvt.

**Comment by NHDaly** [comment]
Assuming that you didn't just make a typo when typing that up in this post, you've spelled my username wrong. 😛 

> `set -g @plugin 'NGDaly/tmux-scroll-copy-mode'`

Should be:
`set -g @plugin 'NHDaly/tmux-scroll-copy-mode'`

I'd _guess_ very strongly that will fix your problem.

**Comment by zeorin** [comment]
@NHDaly Lol, that's just a typo in my issue. Well spotted! But in my `~/.tmux.conf` file it's spelled correctly and still exhibits the behaviour I described.

**Comment by NHDaly** [comment]
:) Haha okay sounds good.

Hmm, that's super weird. Can you start by pasting here the output of `tmux list-keys -T root`?

For example, for me it looks like this:

```
bind-key -T root MouseDown1Pane   select-pane -t = ; send-keys -M
bind-key -T root MouseDown1Status select-window -t =
bind-key -T root MouseDown3Pane   select-pane -m -t =
bind-key -T root MouseDrag1Pane   if-shell -F -t = #{mouse_any_flag} "if -Ft= "#{pane_in_mode}" "copy-mode -M" "send-keys -M"" "copy-mode -M"
bind-key -T root MouseDrag1Border resize-pane -M
bind-key -T root WheelUpPane      if-shell -F -t = #{mouse_any_flag} "send-keys -M" "         if -Ft= '#{alternate_on}'           'send-keys up ; send-keys up ; '           "                          if -Ft= '#{pane_in_mode}'               'send-keys -M ; send-keys -M ; '               'copy-mode -e -t= ; send-keys -M ; send-keys -M ; '           "       "
bind-key -T root WheelDownPane    if-shell -F -t = #{mouse_any_flag} "send-keys -M" "         if -Ft= '#{alternate_on}'           'send-keys down ; send-keys down ; '           ' send-keys -M ; send-keys -M ; '       "
```

**Comment by NHDaly** [comment]
Also, this won't affect anything, but `prevent-scroll-for-fullscreen-alternate-buffer` is deprecated and now it just does the same thing as `emulate-scroll-for-no-mouse-alternate-buffer`, so you can just remove that line from your config. But that shouldn't be the cause of your problem.

**Comment by NHDaly** [comment]
Oops.

**Comment by zeorin** [comment]
The ouput of that command is as follows:

```
bind-key -T root C-h              if-shell "tmux display -p '#{pane_current_command} #T' | grep -iqE '(vim|VIM)'" "send-keys C-h" "select-pane -L"
bind-key -T root C-j              if-shell "tmux display -p '#{pane_current_command} #T' | grep -iqE '(vim|VIM)'" "send-keys C-j" "select-pane -D"
bind-key -T root C-k              if-shell "tmux display -p '#{pane_current_command} #T' | grep -iqE '(vim|VIM)'" "send-keys C-k" "select-pane -U"
bind-key -T root C-l              if-shell "tmux display -p '#{pane_current_command} #T' | grep -iqE '(vim|VIM)'" "send-keys C-l" "select-pane -R"
bind-key -T root C-\              if-shell "tmux display -p '#{pane_current_command} #T' | grep -iqE '(vim|VIM)'" "send-keys C-\" "select-pane -l"
bind-key -T root MouseDown1Pane   select-pane -t = ; send-keys -M
bind-key -T root MouseDown1Status select-window -t =
bind-key -T root MouseDown3Pane   if-shell -F -t = #{mouse_any_flag} "select-pane -t=; send-keys -M" "select-pane -mt="
bind-key -T root MouseDrag1Pane   if-shell -F -t = #{mouse_any_flag} "if -Ft= "#{pane_in_mode}" "copy-mode -M" "send-keys -M"" "copy-mode -M"
bind-key -T root MouseDrag1Border resize-pane -M
bind-key -T root WheelUpPane      if-shell -F -t = #{mouse_any_flag} "send-keys -M" "         if -Ft= ''           'send-keys up ; send-keys up ; send-keys up ; '           "                          if -Ft= '#{pane_in_mode}'               'send-keys -M ; send-keys -M ; send-keys -M ; '               'copy-mode ; send-keys -M ; send-keys -M ; send-keys -M ; '           "       "
bind-key -T root WheelUpStatus    previous-window
bind-key -T root WheelDownPane    if-shell -F -t = #{mouse_any_flag} "send-keys -M" "         if -Ft= ''           'send-keys down ; send-keys down ; send-keys down ; '           ' send-keys -M ; send-keys -M ; send-keys -M ; '       "
bind-key -T root WheelDownStatus  next-window
bind-key -T root M-l              send-keys C-l
bind-key -T root C-S-Up           resize-pane -U 15
bind-key -T root C-S-Down         resize-pane -D 15
bind-key -T root C-S-Left         resize-pane -L 25
bind-key -T root C-S-Right        resize-pane -R 25
```

**Comment by zeorin** [comment]
For reference, my full `~/.tmux.conf` file is here: https://github.com/zeorin/dotfiles/blob/5dd75fb/.tmux.conf

**Comment by NHDaly** [comment]
Hmm, that's super weird. And you're sure your plugin is updated?

Your `WheelUpPane` looks identical to @stfl's above, and I'm pretty sure that's why your seeing the the problem you describe. I'm not sure why it would be set to that value, though.

Can you do me a favor and print what commit number your plugin is at by running this command?:

```
cd $TMUX_PLUGIN_MANAGER_PATH/tmux-scroll-copy-mode/ && git rev-parse HEAD
```

For me, that prints `d157c5fbd0850b2066dc388322b1f29c4290a86e`. But d157c5fb was just a README update I pushed yesterday; you might also see `5e4c864d2f96be01000f692fe0f04cf50128a8df` if you haven't updated today and that should be okay too.

And then run `tmux source ~/.tmux.conf` just to be sure and verify that you still see the same value for `WheelUpPane`.

**Comment by zeorin** [comment]
I found (most) of the cause of these issues. The scripts weren't POSIX-compatible, but on some systems were interpreted by a strict POSIX-compatibility-only shell. I've created a PR: #20, that fixes this.

Lack of mouse scrolling functionality in VIm is still an issue, though.

**Comment by zeorin** [comment]
Actually, Vim scrolling works just fine by sending the up/down arrow keys. I had this in my `.vimrc`:

```
    " unmap keys I shouldn't be using
    inoremap <esc> <nop>
    inoremap <up> <nop>
    inoremap <down> <nop>
    inoremap <left> <nop>
    inoremap <right> <nop>
    nnoremap <up> <nop>
    nnoremap <down> <nop>
    nnoremap <left> <nop>
    nnoremap <right> <nop>
```

Which I'd put there to train myself to only use `hjkl` instead of the arrow keys. That was years ago and I don't need these no-op bindings anymore. As far as I'm concerned this issue is fixed if #20 is merged.

EDIT: Just for posterity's sake, anyone using the [Hard Mode](https://github.com/wikitopian/hardmode) or [Medium Mode](https://github.com/kbarrette/mediummode) plugins will have the same issue.

**Comment by NHDaly** [comment]
Oh awesome, that's a good find.

Hmm, but still though, I think Vim shouldn't be getting `up` arrow keys, it should be getting mouse scroll events.

I am _pretty sure_ this is what the `if-shell -F -t = #{mouse_any_flag} "send-keys -M" "..."` part of the line does: i.e. if the pane already has some sort of mouse interactions bit enabled (such as vim having mouse support turned on) just send the keys through to vim.

Actually, would you please check: do you have mouse-mode enabled in vim? (`:set mouse?` should echo `mouse=a`.)

In fact, I have verified this: on my system, I am getting proper mouse scroll events sent to vim if `mouse=a` and I'm getting `up` arrow keys if `mouse=` (disabled). That is, when I disable mouse mode in vim, tmux converts scrolls to up/down arrow keys. When I _enable_ mouse mode in vim, tmux sends proper mouse wheel events. I can tell, because vim reacts to mouse scroll events by scrolling the background text rather than moving the cursor (until the cursor hits a border), whereas of course it reacts to up/down arrow keys by moving the cursor.

**Comment by zeorin** [comment]
Hi, sorry, fell asleep. In Vim I have mouse mode set as you describe. When I start Vim using `vim -u NONE` (don't load plugins or read any initialization files), there's no scrolling at all. When I then run `:set mouse=a`, it scrolls by moving the cursor and only the file as a whole when the top or bottom is reached. My Vim version is 7.4, patches 1-1689 on my Ubuntu machine.

Perhaps you have a setting in your `.vimrc` (other than `:set mouse=a`) which effects whether scrolling is accepted? Or a terminal override in your `.tmux.conf`?

I use NeoVim mostly, so I'm not that concerned. This might be slightly sub-optimal scrolling behaviour, but when I do have to use Vim instead of NeoVim (e.g. can't install out-of-repo software on a remote machine or something), this is good enough.

IMO, you can close this if you like. But if you want to investigate further, I'd be happy to help.

**Comment by NHDaly** [comment]
Yeah, I'd love to help try to figure this out!

I'll go ahead and close this issue since I think we've covered the reason you and @stfl were seeing broken behavior. Thanks again for the PR. :)

I've opened #21 and we can keep investigating there?

**Comment by stfl** [comment]
Ah thanks. Just had a look again. It works again now.
Thank you.
